parameters:
  type: Physical
  dt: 0.002
  boundaries:
    - l: 20e-6
      closed: false
    - l: 20e-6
      closed: false
    - l: 20e-6
      closed: false
  singularities: []
    # - point: [0.0, 0.0, 0.0]
    #   params:
    #     type: Rotlet
    #     c: [0.0, 1.0e-24, 0.0]
  object_stiffness: 1e-0
  # fluid_temperature: 300.0
  fluid_temperature: 0.0
  fluid_viscosity: 0.001
  # agent_radius: 0.5e-6
  agent_radius: 2.0e-6
  agent_length: 4.0e-6
  agent_linear_spring_stiffness: 1.0e-6
  agent_propulsion_force: 0.5e-14
  # agent_propulsion_force: 0.0
  agent_propulsion_dipole_strength: 0.5e-18
  agent_agent_hydro_a: 0.0
  agent_agent_hydro_b: 0.0
agent_initialization:
  - type: RandomUniformByNumber
    number: 10
  # - type: Explicit
  #   agents:
  #     - r: [0.0, 1.0e-6, 0.0]
  #       u: [1.0, 0.0, 0.0]
  #     - r: [3.0e-6, 0.0e-6, 0.0]
  #       u: [1.0, 0.0, 0.0]
  # - type: RandomUniformByVolumeNumberDensity
  #   volume_number_density: 0.01e17
