parameters:
  type: Physical
  dt: 0.001
  boundaries:
    - l: 80
      closed: false
    - l: 80
      closed: false
    - l: 80
      closed: false
  singularities: []
    # - point: [0.0, 0.0, 0.0]
    #   params:
    #     type: Rotlet
    #     c: [0.0, 1.0, 0.0]
  object_stiffness: 1e-5
  fluid_temperature: 0.0
  fluid_viscosity: 1e-9
  agent_radius: 0.5
  agent_length: 4.0
  agent_propulsion_force: 0.5e-6
agent_initialization:
  # - type: RandomUniformByNumber
  #   number: 100
  # - type: RandomUniformByVolumeNumberDensity
  #   volume_number_density: 0.01e17
  - type: Explicit
    agents:
      - r: [0.0, 0.0, 0.0]
        u: [+1.0   , +0.0   ,  +0.0   ]
      # - r: [+9.0, +0.0   ,  +0.0   ]
      #   u: [-1.0   , +0.0   ,  +0.0   ]
  # - type: Explicit
  #   agents:
  #     - r: [-9.0, +0.0, +0.0]
  #       u: [+1.0   , +0.1   , +0.0   ]
  #     - r: [-9.0, +3.0, +0.0]
  #       u: [+1.0   , +0.0   , +0.0   ]
