parameters:
  type: Physical
  dt: 0.001
  l:
    - 20e-6
    - 20e-6
    - 20e-6
  object_stiffness: 1e15
  fluid_temperature: 0.0
  # fluid_temperature: 300.0
  fluid_viscosity: 0.001
  agent_radius: 2e-6
  agent_aspect_ratio: 2.0
  agent_propulsion_force: 0.5e-12
  agent_propulsion_dipole_strength: 0.5e-18
  agent_agent_hydro_a: 0.0
  agent_agent_hydro_b: 0.0
agent_initialization:
  # type: RandomUniformByVolumeNumberDensity
  # volume_number_density: 0.01e17
  type: RandomUniformByNumber
  number: 10
