parameters:
  type: Physical
  dt: 0.001
  boundaries:
    - l: 100e-6
      closed: false
    - l: 100e-6
      closed: true
    - l: 100e-6
      closed: true
  singularities:
    - point: [0.0, 0.0, 0.0]
      params:
        type: Rotlet
        c: [0.0, 1.0e-15, 0.0]
  object_stiffness: 1e15
  # fluid_temperature: 0.0
  fluid_temperature: 300.0
  fluid_viscosity: 0.001
  agent_radius: 2e-6
  agent_aspect_ratio: 2.0
  agent_propulsion_force: 0.5e-12
  agent_propulsion_dipole_strength: 0.5e-18
  agent_agent_hydro_a: 0.0
  agent_agent_hydro_b: 0.0
agent_initialization:
  - type: RandomUniformByNumber
    number: 400
  # - type: Explicit
  #   agents:
  #     - r: [0.0, 1.0e-6, 0.0]
  #       u: [1.0, 0.0, 0.0]
  #     - r: [3.0e-6, 0.0e-6, 0.0]
  #       u: [1.0, 0.0, 0.0]
  # - type: RandomUniformByVolumeNumberDensity
  #   volume_number_density: 0.01e17
